name: Check
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble test -y
